# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Actian Corporation

---

{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "actianzen.serviceAccountName" . }}
  labels:
    {{- include "actianzen.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
