# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

{{- if not .Values.deployment.sriov }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "nginxcdn.fullname" . }}-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
        app.kubernetes.io/name: {{ template "nginxcdn.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
{{- if .Values.numNodes }}
{{- range $ipIdx := until ( int .Values.numNodes ) }}
    - ipBlock:
        cidr: 192.168.{{ add $ipIdx 1 }}.0/24
{{- end }}
{{- else }}
    - ipBlock:
        cidr: 192.168.1.0/24
{{- end }}
    ports:
    {{- if kindIs "map" .Values.nginx.http.server }}
    - protocol: TCP
      port: {{ default 80 .Values.nginx.http.server.port }}
    - protocol: TCP
      port: {{ default 443 .Values.nginx.http.server.sslport }}
    {{- else }}
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
    {{- end }}
{{- end }}
