# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

{{- $release_name := include "nginxcdn.fullname" . }}

{{- if .Values.CDNNode }}
{{- range $index, $val := .Values.nginx.http.proxy_cache }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $release_name }}-pvc{{ $index }}
spec:
  accessModes:
        - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: {{ upper $val.max_size }}i
  volumeName: {{ $release_name }}-pv{{ $index }}
---
{{- end }}
{{- end }}

