# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

{{- if kindIs "map" .Values.nginx.http.server }}
{{- if eq ( .Values.nginx.http.server.ext_ssl_certificate ) true }}
apiVersion: v1    
kind: Secret
metadata:
  name: {{ template "nginxcdn.fullname" . }}-secret
type: Opaque
data:
{{- if .Values.nginx.http.server.ssl_cert_file }}
  nginx.crt:
    {{ ( .Values.nginx.http.server.ssl_cert_file | b64enc ) | quote }}
{{- else }}
    {{ fail "ssl certificate file missing" }}
{{- end }}
{{- if .Values.nginx.http.server.ssl_key_file }}
  nginx.key:
    {{ ( .Values.nginx.http.server.ssl_key_file | b64enc ) | quote }}
{{- else }}
    {{ fail "ssl certificate key missing" }}
{{- end }}
{{- end }}
{{- end }}
