# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 LINKS Foundation
apiVersion: v1
kind: Service
metadata:
  name: {{ include "links-location-api.fullname" . }}
  labels:
    {{- include "links-location-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    run: location-api
    {{- include "links-location-api.selectorLabels" . | nindent 4 }}
