# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    name: "{{ .Chart.Name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
    spec:
      hostname: ia-web-visualizer
      containers:
        - name: "{{ .Chart.Name }}"
          image: {{ .Values.image }}
          volumeMounts:
            - mountPath: "{{ .Values.eisSecretsPath }}"
              name: etcd-certs
              readOnly: true
          env:
            - name: AppName
              value: "{{ .Values.appName }}"
            - name: DEV_MODE
              value: "{{ .Values.devMode }}"
            - name: PROFILING_MODE
              value: "false"
            - name: ETCD_HOST
              value: ia-etcd-service
            - name: CertType
              value: "zmq,pem"
            - name: ZMQ_RECV_HWM
              value: "50"
            - name: SubTopics
              value: "VideoAnalytics/camera1_stream_results"
            - name: camera1_stream_results_cfg
              value: "zmq_tcp,{{ .Values.publisherPodService }}:{{ .Values.cameraStreamResultsPort }}"
            - name: CONFIGMGR_CERT
              value: "{{ .Values.certPath }}"
            - name: CONFIGMGR_KEY
              value: "{{ .Values.keyPath }}"
            - name: CONFIGMGR_CACERT
              value: "{{ .Values.rootCACertPath }}"
            - name: no_proxy
              value: "{{ .Values.eis_no_proxy }}"
      hostNetwork: false
      volumes:
        - name: etcd-certs
          projected:
            sources:
            - secret:
                name: {{ .Values.secrets.etcdCertsSecretName }}
            - secret:
                name: {{ .Values.secrets.rootCaSecretName }}
