# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 ClearBlade, Inc. All rights reserved.

apiVersion: v1
name: clearblade-edge
type: application
version: 0.1.0
appVersion: 1.0.0
description: ClearBlade Edge Application
