# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---
  
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.etcdCertsSecretName }}
type: Opaque
data:
{{ (.Files.Glob "secrets/*").AsSecrets | indent 2 }}
