# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Radisys Corporation

{{- $release_name := include "mrf.fullname" . }}

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "mrf.fullname" . }}-rootfs-pv0
  labels:
        type: local
spec:
  capacity:
        storage: {{ required "Rootfs Volume Size required.. Missing" .Values.PersistentVolume.rootfs.size }}
  accessModes:
        - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
        path: {{ required "Rootfs Volume0: Local Path Missing" .Values.PersistentVolume.rootfs.path }}  
